version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.8
      - test-3.9
      - test-3.10
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7.4-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev --python `which python`
      - run:
          name: Run tests
          command: |
            ./test.sh
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.0-buster
  test-3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9.0-buster
  test-3.10:
    <<: *test-template
    docker:
      - image: circleci/python:3.10.0-buster
